{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <DemoPyTest.test_class.TestClass object at 0x036ABBF0>\n\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x, \"check\")\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\ntest_class.py:21: AssertionError"}, "start": 1592389159417, "stop": 1592389159417, "uuid": "881c69a6-a52d-449f-b35c-e9afb7ac82ad", "historyId": "cca081f1c320efa44fffe5d884236360", "testCaseId": "9e2269e6af13cd7747e18ca37f3d74ba", "fullName": "test_class.TestClass#test_two", "labels": [{"name": "suite", "value": "test_class"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "R10459"}, {"name": "thread", "value": "23444-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_class"}]}