{"name": "test_d_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert (2 - 1) == 0", "trace": "self = <DemoPyTest.b_folder.test_d.TestD object at 0x03770170>\n\n    @pytest.mark.success\n    def test_d_1(self):\n>       assert 2 - 1 == 0\nE       assert (2 - 1) == 0\n\nb_folder\\test_d.py:18: AssertionError"}, "start": 1592389159468, "stop": 1592389159469, "uuid": "54be66e1-0562-408f-8cdd-ff52497037f4", "historyId": "9db47564b5a145aeb04158a60eda3278", "testCaseId": "b3a2dd62902db8c79f79fd47a71be897", "fullName": "b_folder.test_d.TestD#test_d_1", "labels": [{"name": "tag", "value": "success"}, {"name": "parentSuite", "value": "b_folder"}, {"name": "suite", "value": "test_d"}, {"name": "subSuite", "value": "TestD"}, {"name": "host", "value": "R10459"}, {"name": "thread", "value": "23444-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "b_folder.test_d"}]}